apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxrc
spec:
  replicas: 2
  selector:
    app: nginxapp
  template:
    metadata:
      name: nginx
      labels: 
        app: nginxapp
    spec:
      containers:
      - name: nginxcontainer
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: nginxsvc
spec:
  type: NodePort
  selector:
    app: nginxapp
  ports:
    - port: 80