apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-spring-host-vol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/db
    type: Directory