apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: word
  template:
    metadata:
      labels:
        app: word
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service
            - name: WORDPRESS_DB_USER
              value: devdb
            - name: WORDPRESS_DB_PASSWORD
              value: devdb@123
            - name: WORDPRESS_DB_NAME
              value: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: word-service
spec:
  type: NodePort
  selector:
    app: word
  ports:
    - port: 80
      targetPort: 80
