apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxpod
  labels:
    app: nginx
spec:
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-con
        image: nginx:1.27
        ports:
        - containerPort: 80

#kubectl rollout status nginxpod
#kubectl rollout status deployment.apps/nginxpod
#kubectl rollout history deployment.apps/nginxpod
#kubectl rollout undo <deployment-name>
#kubectl rollout undo <deployment-name> --to-revision=2
#kubectl scale deployment/nginx-deployment --replicas=10
#kubectl rollout pause deployment/nginx-deployment
#kubectl rollout resume deployment/nginx-deployment
